;; 01-basis.lisp — quote, if, and/or/not, cond
;; Konvention: ein Fall pro Zeile, kein Mehrzeiler, keine case-sensitiven Strings.
(if t 1 2)
(if nil 1 2)
(if nil 1)
(if 0 1 2)
(if '() 'leer 'voll)
'abc
''abc
'(1 (2 3) 4)
(quote ())
(and)
(and 1)
(and nil 1)
(and 1 2 3)
(and nil (error "darf nicht evaluiert werden"))
(or)
(or nil nil 3)
(or 1 2)
(or nil)
(or 1 (error "darf nicht evaluiert werden"))
(not t)
(not nil)
(not '())
(not 0)
(cond (nil 1) (t 2))
(cond (t 1) (t 2))
(cond (nil 1))
(cond ((+ 1 1) 2) (t 3))
(cond (t))
