;; 02-let-lambda.lisp — let, let*, lambda, function, flet, labels, defun
(let ((a 1) (b 2)) (+ a b))
(let ((a 1)) (let ((a 2)) a))
(let* ((a 1) (b (+ a 1))) (list a b))
(let ((a 1) (b a)) b)
((lambda (x) (* x x)) 5)
((lambda (x y) (+ x y)) 3 4)
((lambda (&optional (x 9)) x))
((lambda (&optional (x 9)) x) 1)
((lambda (&rest xs) (length xs)) 1 2 3)
(funcall (function +) 1 2 3)
(function +)
#'(lambda (x) x)
(flet ((doppelt (x) (* 2 x))) (doppelt 21))
(flet ((a () 1) (b () (a))) (b))
(labels ((fak (n) (if (= n 0) 1 (* n (fak (- n 1)))))) (fak 5))
(labels ((gerade (n) (if (= n 0) t (ungerade (- n 1)))) (ungerade (n) (if (= n 0) nil (gerade (- n 1))))) (gerade 10))
(defun konst () 42)
(konst)
(defun letztes (xs) (if (null (cdr xs)) (car xs) (letztes (cdr xs))))
(letztes '(1 2 3))
((lambda () 1 2 3))
(defun multi () 1 2 3)
(multi)
