;; 03-block-catch.lisp — block/return-from, catch/throw, unwind-protect
(block nil 1 2 3)
(block a (return-from a 42) 1)
(block a 1 (return-from a 7) 2)
(block a (block b (return-from a 1)) 2)
(defun frueh (x) (block raus (if x (return-from raus 'ja)) 'nein))
(frueh t)
(frueh nil)
(catch 'f (throw 'f 42) 1)
(catch 'f 1 2 3)
(catch 'f (+ 1 (throw 'f 5)))
(catch 'a (catch 'b (throw 'a 1)) 2)
(catch nil (throw nil 'leer))
(defun werfer () (throw 'oben 'geworfen))
(catch 'oben (werfer))
(list (catch 'f (throw 'f 1)) (catch 'f (throw 'f 2)))
(unwind-protect (values 1 2) 'aufraeumen)
(defun uw-test () (let ((x 0)) (list (catch 'f (unwind-protect (throw 'f 'raus) (setq x 99))) x)))
(uw-test)
(block nil (return-from nil 42) 1)
(block nil 1 (return 7) 2)
