;; 04-seq.lisp — progn, prog1, prog2, do, do*, dolist, dotimes, tagbody/go
(progn)
(progn 1)
(progn 1 2 3)
(prog1 1 2 3)
(prog1 (list 1) (list 2))
(prog2 0 1 2 3)
(let ((x 0)) (progn (setq x 1) (setq x (+ x 1)) x))
(do ((i 0 (+ i 1)) (s 0 (+ s i))) ((= i 5) s))
(do ((i 0 (+ i 1))) ((> i 3) i))
(do ((i 0 (+ i 1)) (j 10 (- j 1))) ((= i j) (list i j)))
(do* ((i 0 (+ i 1)) (s i (+ s i))) ((= i 4) s))
(do* ((x 1) (y (* x 2))) (t (list x y)))
(do* () (t 'sofort))
(do* ((i 0 (+ i 1))) ((> i 3) 'fertig))
(do* ((i 0 (+ i 1)) (j 0 (+ j i))) ((= i 3) (list i j)))
(dolist (x '(1 2 3) 'fertig) x)
(let ((s 0)) (dolist (x '(1 2 3) s) (setq s (+ s x))))
(dolist (x '() 'leer) x)
(dotimes (i 4 'ende) i)
(let ((s 0)) (dotimes (i 5 s) (setq s (+ s i))))
(let ((x 0)) (tagbody (setq x 1) (go ende) (setq x 99) ende) x)
(let ((x 0) (i 0)) (tagbody schleife (setq x (+ x 1)) (setq i (+ i 1)) (if (< i 3) (go schleife))) x)
(tagbody (go mitte) mitte)
(let ((xs '())) (tagbody start (if (> (length xs) 2) (go ende)) (setq xs (cons (length xs) xs)) (go start) ende) (reverse xs))
(let ((xs (list 1 2 3)) (i 1)) (setf (nth (+ i 1) xs) 77) xs)
(let ((xs (list 1 2 3))) (setf (nth 0 xs) 'a) (setf (nth 2 xs) 'c) xs)
