;; 06-multiple-values.lisp — values + MV-Familie + Primärwert-Regeln
(values)
(values 1)
(multiple-value-list (values 1 2 3))
(multiple-value-list (values))
(multiple-value-list (floor 7 2))
(multiple-value-list (floor -7 2))
(floor 7 2)
(+ (values 1 2) 10)
(list (values 1 2 3))
(multiple-value-bind (a b) (floor 7 2) (list a b))
(multiple-value-bind (a b c) (values 1 2) (list a b c))
(multiple-value-bind () (values 1 2) 'keine)
(multiple-value-bind (q r) (floor 17 5) (+ q r))
(multiple-value-call #'+ (values 1 2) 3 (values 4 5))
(multiple-value-call #'list (floor 7 2))
(multiple-value-call #'+)
(multiple-value-prog1 (values 1 2) 'nebenwirkung)
(multiple-value-list (multiple-value-prog1 (values 1 2) 99))
(nth-value 0 (floor 7 2))
(nth-value 1 (floor 7 2))
(nth-value 5 (values 1 2))
(multiple-value-setq (x y) (floor 7 2))
(defun zwei-werte () (values 'erster 'zweiter))
(zwei-werte)
(multiple-value-list (zwei-werte))
(let ((a 1)) (multiple-value-setq (a b) (values 10 20)) (list a b))
(multiple-value-list (gethash 'nix (make-hash-table)))
