;; 07-macro.lisp — defmacro, macroexpand, macrolet, symbol-macrolet
(defmacro plus-eins (x) (list '+ x 1))
(plus-eins 41)
(defmacro tausch (a b) (list 'let (list (list 'tmp a)) (list 'setq a b) (list 'setq b 'tmp)))
(macroexpand '(plus-eins 5))
(defmacro wenn (test &rest body) (list 'if test (cons 'progn body)))
(wenn t 1 2 3)
(macrolet ((doppelt (x) (list '* 2 x))) (doppelt 21))
(macrolet ((a () 1)) (a))
(macrolet ((m () 'global)) (defun ruft-m () (m)))
(symbol-macrolet ((x 42)) x)
(symbol-macrolet ((x (+ 1 2))) (* x 10))
(let ((y 5)) (symbol-macrolet ((x y)) (setq x 9) y))
(symbol-macrolet ((x 1)) (let ((x 2)) x))
(symbol-macrolet ((x 5)) ((lambda (x) (+ x 1)) 9))
(symbol-macrolet ((x 1)) (dolist (x '(7 8) x) x))
(defmacro mit-tmp (wert &body body) (list 'let (list (list 'tmp wert)) (cons 'progn body)))
(mit-tmp 10 (setq tmp (+ tmp 1)) tmp)
