;; 08-dekl.lisp — declare, locally, the, eval-when, progv, load-time-value
(let ((x 1)) (declare (ignore x)) 2)
((lambda (x) (declare (type fixnum x)) (+ x 1)) 5)
(locally 1 2 3)
(locally (declare) 42)
(the fixnum (+ 1 2))
(the t 'irgendwas)
(progv '(dyn-var) '(99) dyn-var)
(progv '() '() 7)
(let ((dyn-var 1)) (progv '(dyn-var) '(2) dyn-var))
(eval-when (:execute) 5)
(eval-when (:compile-toplevel) 5)
(eval-when (:load-toplevel) 5)
(eval-when (eval) 5)
(eval-when (:execute :load-toplevel) 1 2 3)
(defun mit-decl (x y) (declare (ignore y)) (* x 2))
(mit-decl 3 99)
(multiple-value-list (the t (values 1 2)))
(locally (declare (ignore x)) 7)
