;; 09-hashtables.lisp — make-hash-table, gethash (MV!), setf-gethash, remhash,
;; clrhash, hash-table-count/-p, maphash. Reihenfolge zählt (stateful).
(defvar *h* (make-hash-table))
(hash-table-p *h*)
(hash-table-p 'x)
(hash-table-count *h*)
(gethash 'a *h*)
(multiple-value-list (gethash 'a *h*))
(gethash 'a *h* 'def)
(setf (gethash 'a *h*) 1)
(setf (gethash 'b *h*) 2)
(gethash 'a *h*)
(multiple-value-list (gethash 'a *h*))
(hash-table-count *h*)
(remhash 'a *h*)
(gethash 'a *h*)
(multiple-value-list (gethash 'a *h*))
(remhash 'a *h*)
(hash-table-count *h*)
(setf (gethash 'x *h*) 10)
(setf (gethash 'y *h*) 20)
(let ((sum 0)) (maphash (lambda (k v) (setq sum (+ sum v))) *h*) sum)
(let ((seen 0)) (maphash (lambda (k v) (setq seen (+ seen 1))) *h*) seen)
(clrhash *h*)
(hash-table-count *h*)
(defvar *h2* (make-hash-table :test 'equal))
(setf (gethash "s" *h2*) 5)
(gethash "s" *h2*)
(setf (gethash '(1 2) *h2*) 7)
(gethash (list 1 2) *h2*)
(defvar *h3* (make-hash-table :test 'eq))
(setf (gethash 'k *h3*) 9)
(gethash 'k *h3*)
