# **********************************************************************
#  tools/gen-training/data.py
#  Autor    : Gerhard Quell - gquell@skequell.de
#  CoAutor  : claude sonnet 4.6
#  Copyright: 2026 Gerhard Quell - SKEQuell
#  Erstellt : 20260623
# **********************************************************************
# Rohdaten für golisp-tutorial.md und golisp-anki.json.
# Strings sind absichtlich in Python-Triple-Quotes, damit Backticks
# und doppelte Anführungszeichen in Lisp-Beispielen nicht escapet
# werden müssen.
# **********************************************************************

FUNCS = [
    # ---- Spezialformen ----
    dict(cat="Spezialformen", name="quote", syntax="(quote ausdruck)  bzw.  'ausdruck",
         desc="Verhindert die Auswertung eines Ausdrucks und gibt ihn als Datenstruktur zurück.",
         examples=["(quote (+ 1 2))", "'(+ 1 2)", "(car '(a b c))"]),
    dict(cat="Spezialformen", name="if", syntax="(if bedingung dann [sonst])",
         desc="Wertet dann aus, wenn die Bedingung wahr ist, sonst den optionalen else-Zweig.",
         examples=["(if t 1 2)", "(if nil 'ja 'nein)", "(if (> 3 2) 'größer)"]),
    dict(cat="Spezialformen", name="define", syntax="(define symbol wert)  bzw.  (setq symbol wert)",
         desc="Bindet einen Wert an einen Namen im aktuellen Environment.",
         examples=["(define x 10)", "(setq y 20)", "(+ x y)"]),
    dict(cat="Spezialformen", name="setq", syntax="(setq symbol wert)",
         desc="Alias für define – bindet einen Wert an einen Namen.",
         examples=["(setq antwort 42)"]),
    dict(cat="Spezialformen", name="defun", syntax="(defun name (parameter ...) body ...)",
         desc="Definiert eine benannte Funktion. Mehrere Body-Ausdrücke werden implizit in begin gewrappt.",
         examples=["(defun quadrat (x) (* x x))", "(quadrat 7)", "(defun add (a b) (print a) (+ a b))"]),
    dict(cat="Spezialformen", name="lambda", syntax="(lambda (parameter ...) body ...)",
         desc="Erzeugt eine anonyme Funktion bzw. Closure.",
         examples=["((lambda (x) (* x 2)) 5)", "(define doppel (lambda (x) (* 2 x)))", "(doppel 4)"]),
    dict(cat="Spezialformen", name="let", syntax="(let ((var wert) ...) body ...)",
         desc="Bindet Variablen parallel – alle Werte werden im äußeren Environment ausgewertet.",
         examples=["(let ((a 1) (b 2)) (+ a b))", "(let ((x 5) (y 10)) (list x y))"]),
    dict(cat="Spezialformen", name="let*", syntax="(let* ((var wert) ...) body ...)",
         desc="Bindet Variablen sequentiell – jede Bindung sieht die vorherigen.",
         examples=["(let* ((x 1) (y (+ x 1))) y)", "(let* ((a 2) (b (* a 3))) (+ a b))"]),
    dict(cat="Spezialformen", name="begin", syntax="(begin ausdruck ...)",
         desc="Wertet Ausdrücke nacheinander aus und gibt das Ergebnis des letzten zurück.",
         examples=["(begin (print 1) (print 2) 3)", "(begin (define x 1) (set! x 2) x)"]),
    dict(cat="Spezialformen", name="set!", syntax="(set! symbol wert)",
         desc="Ändert den Wert einer bestehenden Variablen.",
         examples=["(define a 1)", "(set! a 99)", "a"]),
    dict(cat="Spezialformen", name="setq*", syntax="(setq* var1 wert1 var2 wert2 ...)",
         desc="Setzt mehrere Variablen sequentiell; fehlende Variablen werden neu angelegt.",
         examples=["(setq* a 1 b (+ a 1) c (+ b 1))", "(list a b c)"]),
    dict(cat="Spezialformen", name="defmacro", syntax="(defmacro name (parameter ...) body ...)",
         desc="Definiert ein Makro, das zur Expandierungszeit transformiert wird.",
         examples=["(defmacro unless (test . body) `(if ,test () (begin ,@body)))", "(unless nil 'ok)"]),
    dict(cat="Spezialformen", name="macroexpand", syntax="(macroexpand form)",
         desc="Expandiert Makros einmal auf Top-Level und gibt das Ergebnis zurück.",
         examples=["(defmacro doppelt (x) `(+ ,x ,x))", "(macroexpand (doppelt 5))"]),
    dict(cat="Spezialformen", name="macroexpand-all", syntax="(macroexpand-all form)",
         desc="Expandiert Makros rekursiv in allen Subformen.",
         examples=["(macroexpand-all (doppelt (+ 1 2)))"]),
    dict(cat="Spezialformen", name="function", syntax="(function ausdruck)",
         desc="Wertet den übergebenen Ausdruck aus und gibt seinen Wert zurück.",
         examples=["(function +)"]),
    dict(cat="Spezialformen", name="flet", syntax="(flet ((name (parameter ...) body ...) ...) body ...)",
         desc="Definiert lokale Funktionen, die über das äußere Environment schließen.",
         examples=["(flet ((inc (x) (+ x 1))) (inc 5))"]),
    dict(cat="Spezialformen", name="labels", syntax="(labels ((name (parameter ...) body ...) ...) body ...)",
         desc="Wie flet, aber die lokalen Funktionen können sich gegenseitig rekursiv aufrufen.",
         examples=["(labels ((fac (n) (if (= n 0) 1 (* n (fac (- n 1)))))) (fac 5))"]),
    dict(cat="Spezialformen", name="block", syntax="(block name body ...)",
         desc="Benannter Block; return-from kann ihn vorzeitig verlassen.",
         examples=["(block aus (return-from aus 42) (print 'nie))"]),
    dict(cat="Spezialformen", name="return-from", syntax="(return-from name [wert])",
         desc="Verlässt den benannten Block nicht-lokal und liefert den optionalen Wert.",
         examples=["(block outer (return-from outer 99) 'unten)"]),
    dict(cat="Spezialformen", name="mapcar", syntax="(mapcar funktion liste)",
         desc="Wendet eine Funktion auf jedes Element einer Liste an und liefert die Ergebnisliste.",
         examples=["(mapcar (lambda (x) (* x x)) '(1 2 3))", "(mapcar atom? '(1 (2 3) \"a\"))"]),
    dict(cat="Spezialformen", name="load", syntax="(load \"datei.lisp\")",
         desc="Lädt eine Lisp-Datei, wertet alle enthaltenen Ausdrücke aus und gibt das letzte Ergebnis zurück.",
         examples=["(load \"stdlib.lisp\")"]),
    dict(cat="Spezialformen", name="and", syntax="(and ausdruck ...)",
         desc="Wertet Ausdrücke von links nach rechts aus und bricht bei nil ab. Liefert den letzten wahren Wert.",
         examples=["(and 1 2 3)", "(and t nil 'x)", "(and)"]),
    dict(cat="Spezialformen", name="or", syntax="(or ausdruck ...)",
         desc="Wertet Ausdrücke von links nach rechts aus und liefert den ersten wahren Wert, sonst nil.",
         examples=["(or nil 'a 'b)", "(or nil nil)", "(or 0 'x)"]),
    dict(cat="Spezialformen", name="not", syntax="(not x)",
         desc="Gibt t zurück, wenn x falsch (nil) ist, sonst nil.",
         examples=["(not nil)", "(not t)", "(not 0)"]),
    dict(cat="Spezialformen", name="cond", syntax="(cond (test body ...) ... [(else body ...)])",
         desc="Verzweigungskette; der erste wahre Test bestimmt den ausgeführten Body.",
         examples=["(cond ((= 1 2) 'nein) (t 'ja))", "(cond ((> 5 3) 'größer) (else 'kleiner))"]),
    dict(cat="Spezialformen", name="case", syntax="(case schlüssel ((wert ...) body ...) ... [(else body ...)])",
         desc="Wählt einen Zweig durch strukturelle Gleichheit (equal?) des Schlüssels aus.",
         examples=["(case 'b ((a) 1) ((b c) 2) (else 3))", "(case 5 ((1 2 3) \"klein\") ((4 5 6) \"mittel\"))"]),
    dict(cat="Spezialformen", name="while", syntax="(while test body ...)",
         desc="Wertet den Body so lange aus, wie der Test wahr ist. Gibt nil zurück.",
         examples=["(define i 0)", "(while (< i 3) (print i) (set! i (+ i 1)))"]),
    dict(cat="Spezialformen", name="do", syntax="(do ((var init schritt) ...) (test ergebnis) body ...)",
         desc="Scheme-artige Schleife mit parallelen Bindungen, Abbruchtest und optionalem Body.",
         examples=["(do ((i 0 (+ i 1))) ((= i 3) i) (print i))", "(do ((x 1 (* x 2)) (n 0 (+ n 1))) ((> x 10) n))"]),
    dict(cat="Spezialformen", name="quasiquote", syntax="(quasiquote ausdruck)  bzw.  `ausdruck",
         desc="Wie quote, erlaubt aber unquote (,x) und unquote-splice (,@x) innerhalb.",
         examples=["(define x 5)", "`(liste ,x)", "`(a ,@'(b c))"]),
    dict(cat="Spezialformen", name="eval", syntax="(eval ausdruck)",
         desc="Wertet einen bereits ausgewerteten Ausdruck nochmals im globalen Environment aus.",
         examples=["(eval '(+ 1 2))", "(define code '(+ 3 4))", "(eval code)"]),
    dict(cat="Spezialformen", name="catch", syntax="(catch body handler)",
         desc="Fängt Fehler im Body ab und ruft handler mit der Fehler-Cell auf.",
         examples=["(catch (error \"ups\") (lambda (e) (list 'fehler e)))", "(catch (/ 1 0) (lambda (e) 'recovered))"]),
    dict(cat="Spezialformen", name="parfunc", syntax="(parfunc ergebnis [:timeout n] ausdruck ...)",
         desc="Wertet alle Ausdrücke parallel aus, speichert die Ergebnisliste in ergebnis und gibt sie zurück.",
         examples=["(parfunc ergebnis (+ 1 2) (* 3 4) (- 10 5))", "(car ergebnis)"]),
    dict(cat="Spezialformen", name="lock", syntax="(lock mutex ausdruck ...)",
         desc="Führt die Ausdrücke atomar unter dem angegebenen Mutex aus.",
         examples=["(define m (lock-make))", "(define x 0)", "(lock m (set! x (+ x 1)) (set! x (+ x 1)))", "x"]),

    # ---- Arithmetik ----
    dict(cat="Arithmetik", name="+", syntax="(+ zahl ...)", desc="Addiert alle übergebenen Zahlen.",
         examples=["(+ 1 2 3)", "(+ 5.5 4.5)"]),
    dict(cat="Arithmetik", name="-", syntax="(- zahl ...)  bzw.  (- x y)", desc="Subtrahiert die folgenden Zahlen von der ersten. Ohne Argumente liefert es 0.",
         examples=["(- 10 3)", "(- 5)"]),
    dict(cat="Arithmetik", name="*", syntax="(* zahl ...)", desc="Multipliziert alle übergebenen Zahlen.",
         examples=["(* 2 3 4)", "(* 7)"]),
    dict(cat="Arithmetik", name="/", syntax="(/ x y)", desc="Dividiert x durch y. Fehler bei Division durch 0.",
         examples=["(/ 10 2)", "(/ 1 4)"]),
    dict(cat="Arithmetik", name="mod", syntax="(mod x y)", desc="Liefert den Rest der Division x durch y (Gleitkomma).",
         examples=["(mod 10 3)", "(mod 7.5 2.5)"]),
    dict(cat="Arithmetik", name="remainder", syntax="(remainder x y)", desc="Alias für mod.",
         examples=["(remainder 10 3)"]),
    dict(cat="Arithmetik", name="abs", syntax="(abs x)", desc="Liefert den absoluten Betrag einer Zahl.",
         examples=["(abs -5)", "(abs -3.14)"]),
    dict(cat="Arithmetik", name="random", syntax="(random)  bzw.  (random n)",
         desc="Liefert eine Zufallszahl. Ohne Argument eine große ganze Zahl, mit n einen Wert von 0 bis n-1.",
         examples=["(random 6)", "(random 100)"]),

    # ---- Vergleiche ----
    dict(cat="Vergleiche", name="=", syntax="(= x y)", desc="Numerische Gleichheit.",
         examples=["(= 5 5)", "(= 1 2)"]),
    dict(cat="Vergleiche", name="<", syntax="(< x y)", desc="Numerisch kleiner.",
         examples=["(< 2 5)", "(< 5 2)"]),
    dict(cat="Vergleiche", name=">", syntax="(> x y)", desc="Numerisch größer.",
         examples=["(> 5 2)", "(> 2 5)"]),
    dict(cat="Vergleiche", name=">=", syntax="(>= x y)", desc="Numerisch größer oder gleich.",
         examples=["(>= 5 5)"]),
    dict(cat="Vergleiche", name="<=", syntax="(<= x y)", desc="Numerisch kleiner oder gleich.",
         examples=["(<= 3 7)"]),
    dict(cat="Vergleiche", name="equal?", syntax="(equal? x y)", desc="Strukturelle Gleichheit (rekursiv für Listen).",
         examples=["(equal? '(1 2) '(1 2))", "(equal? 'a 'a)", "(equal? 5 5)"]),
    dict(cat="Vergleiche", name="eq", syntax="(eq x y)", desc="Pointer-Identität – prüft, ob beide Argumente dasselbe Objekt im Speicher sind.",
         examples=["(eq nil nil)", "(eq (list) (list))", "(eq 'foo 'foo)"]),
    dict(cat="Vergleiche", name="eq?", syntax="(eq? x y)", desc="Alias für eq.",
         examples=["(eq? nil nil)"]),

    # ---- Typ-Prädikate ----
    dict(cat="Typ-Prädikate", name="string?", syntax="(string? x)", desc="Gibt t zurück, wenn x ein String ist.",
         examples=["(string? \"hallo\")", "(string? 42)"]),
    dict(cat="Typ-Prädikate", name="number?", syntax="(number? x)", desc="Gibt t zurück, wenn x eine Zahl ist.",
         examples=["(number? 42)", "(number? \"42\")"]),
    dict(cat="Typ-Prädikate", name="list?", syntax="(list? x)", desc="Gibt t zurück, wenn x eine Liste oder nil ist.",
         examples=["(list? '(1 2))", "(list? nil)", "(list? 5)"]),
    dict(cat="Typ-Prädikate", name="symbol?", syntax="(symbol? x)", desc="Gibt t zurück, wenn x ein Symbol (Atom) ist.",
         examples=["(symbol? 'foo)", "(symbol? \"foo\")"]),
    dict(cat="Typ-Prädikate", name="atom?", syntax="(atom? x)", desc="Alias für atom – gibt t zurück, wenn x kein Cons/Liste ist.",
         examples=["(atom? 5)", "(atom? '(1 2))"]),
    dict(cat="Typ-Prädikate", name="null?", syntax="(null? x)", desc="Alias für null – gibt t zurück, wenn x nil ist.",
         examples=["(null? nil)", "(null? '(1))"]),
    dict(cat="Typ-Prädikate", name="atom", syntax="(atom x)", desc="Gibt t zurück, wenn x kein Cons/Liste ist.",
         examples=["(atom 5)", "(atom 'x)", "(atom '(1 2))"]),
    dict(cat="Typ-Prädikate", name="null", syntax="(null x)", desc="Gibt t zurück, wenn x nil ist.",
         examples=["(null nil)", "(null '())", "(null '(1))"]),

    # ---- Listen ----
    dict(cat="Listen", name="car", syntax="(car liste)", desc="Liefert das erste Element einer Liste.",
         examples=["(car '(a b c))", "(car '(1 2))"]),
    dict(cat="Listen", name="cdr", syntax="(cdr liste)", desc="Liefert die Restliste ohne das erste Element.",
         examples=["(cdr '(a b c))", "(cdr '(1))"]),
    dict(cat="Listen", name="cons", syntax="(cons x liste)", desc="Fügt x als neues Kopfelement vor eine Liste.",
         examples=["(cons 1 '(2 3))", "(cons 'a nil)"]),
    dict(cat="Listen", name="list", syntax="(list element ...)", desc="Erzeugt eine neue Liste aus den Argumenten.",
         examples=["(list 1 2 3)", "(list 'a 'b)"]),
    dict(cat="Listen", name="append", syntax="(append liste element)", desc="Hängt ein einzelnes Element an das Ende einer Liste an.",
         examples=["(append '(1 2) 3)", "(append '(a) 'b)"]),
    dict(cat="Listen", name="apply", syntax="(apply funktion arg1 ... liste)",
         desc="Wendet eine Funktion an; das letzte Argument wird als Liste gesplict.",
         examples=["(apply + '(1 2 3))", "(apply + 1 2 '(3 4))"]),
    dict(cat="Listen", name="funcall", syntax="(funcall funktion arg ...)", desc="Ruft eine Funktion mit den angegebenen Argumenten auf.",
         examples=["(funcall + 1 2 3)", "(funcall (lambda (x) (* x x)) 6)"]),

    # ---- Strings ----
    dict(cat="Strings", name="string-length", syntax="(string-length str)", desc="Liefert die Anzahl der Zeichen (Runes) eines Strings.",
         examples=["(string-length \"Hallo\")", "(string-length \"αβγ\")"]),
    dict(cat="Strings", name="string-append", syntax="(string-append str ...)", desc="Verkettet mehrere Strings zu einem neuen String.",
         examples=["(string-append \"Hallo\" \" \" \"Welt\")", "(string-append \"a\" \"b\" \"c\")"]),
    dict(cat="Strings", name="substring", syntax="(substring str start end)",
         desc="Liefert den Teilstring von start (inklusiv) bis end (exklusiv).",
         examples=["(substring \"Hallo\" 0 2)", "(substring \"Welt\" 1 3)"]),
    dict(cat="Strings", name="string-upcase", syntax="(string-upcase str)", desc="Wandelt einen String in Großbuchstaben um.",
         examples=["(string-upcase \"hallo\")"]),
    dict(cat="Strings", name="string-downcase", syntax="(string-downcase str)", desc="Wandelt einen String in Kleinbuchstaben um.",
         examples=["(string-downcase \"HALLO\")"]),
    dict(cat="Strings", name="string->number", syntax="(string->number str)", desc="Parst einen String als Zahl.",
         examples=["(string->number \"42\")", "(string->number \"3.14\")"]),
    dict(cat="Strings", name="number->string", syntax="(number->string zahl)", desc="Wandelt eine Zahl in einen String um.",
         examples=["(number->string 42)", "(number->string 3.14)"]),
    dict(cat="Strings", name="string->list", syntax="(string->list str)", desc="Wandelt einen String in eine Liste von Einzelzeichen-Strings um.",
         examples=["(string->list \"abc\")"]),
    dict(cat="Strings", name="list->string", syntax="(list->string liste)", desc="Verkettet eine Liste von Strings zu einem String.",
         examples=["(list->string '(\"a\" \"b\" \"c\"))"]),
    dict(cat="Strings", name="string-replace", syntax="(string-replace str alt neu)", desc="Ersetzt alle Vorkommen von alt durch neu.",
         examples=["(string-replace \"Hallo Welt\" \"Welt\" \"GoLisp\")"]),
    dict(cat="Strings", name="string-trim", syntax="(string-trim str)", desc="Entfernt führende und abschließende Leerzeichen.",
         examples=["(string-trim \"  hallo  \")"]),
    dict(cat="Strings", name="string-contains", syntax="(string-contains str sub)", desc="Gibt t zurück, wenn sub in str enthalten ist.",
         examples=["(string-contains \"Hallo\" \"all\")", "(string-contains \"Hallo\" \"xyz\")"]),

    # ---- Ein-/Ausgabe ----
    dict(cat="Ein-/Ausgabe", name="print", syntax="(print wert ...)",
         desc="Gibt Werte ohne abschließenden Zeilenumbruch auf stdout aus. Rückgabewert ist das letzte Argument.",
         examples=["(print \"Hallo\")", "(print 1 \" \" 2)"]),
    dict(cat="Ein-/Ausgabe", name="println", syntax="(println wert ...)",
         desc="Gibt Werte mit abschließendem Zeilenumbruch auf stdout aus. Rückgabewert ist das letzte Argument.",
         examples=["(println \"Zeile\")", "(println 1 2 3)"]),
    dict(cat="Ein-/Ausgabe", name="read", syntax="(read str)", desc="Parst einen String und gibt die entsprechende Lisp-Datenstruktur zurück.",
         examples=["(read \"(+ 1 2)\")", "(car (read \"(a b c)\"))"]),

    # ---- Fehler ----
    dict(cat="Fehler", name="error", syntax="(error wert)",
         desc="Signalisiert einen Lisp-Laufzeitfehler, der von catch aufgefangen werden kann.",
         examples=["(error \"etwas ist schief\")", "(catch (error 'x) (lambda (e) (println e)))"]),

    # ---- Makro-Hilfe ----
    dict(cat="Makro-Hilfe", name="gensym", syntax="(gensym)", desc="Erzeugt ein eindeutiges Symbol für Makros.",
         examples=["(gensym)", "(gensym)"]),

    # ---- Datei-I/O ----
    dict(cat="Datei-I/O", name="file-write", syntax="(file-write \"pfad\" inhalt ...)", desc="Schreibt Inhalte in eine Datei (überschreibt).",
         examples=["(system \"mkdir -p ./tmp\")", "(file-write \"./tmp/demo.txt\" \"Hallo\")", "(file-write \"./tmp/zahlen.txt\" 1 \" \" 2)"]),
    dict(cat="Datei-I/O", name="file-append", syntax="(file-append \"pfad\" inhalt ...)", desc="Hängt Inhalte an eine Datei an.",
         examples=["(system \"mkdir -p ./tmp\")", "(file-write \"./tmp/demo.txt\" \"Hallo\")", "(file-append \"./tmp/demo.txt\" \" Welt\")"]),
    dict(cat="Datei-I/O", name="file-read", syntax="(file-read \"pfad\")", desc="Liest den Inhalt einer Datei als String.",
         examples=["(system \"mkdir -p ./tmp\")", "(file-write \"./tmp/demo.txt\" \"Hallo\")", "(file-read \"./tmp/demo.txt\")"]),
    dict(cat="Datei-I/O", name="file-exists?", syntax="(file-exists? \"pfad\")", desc="Gibt t zurück, wenn die Datei existiert.",
         examples=["(system \"mkdir -p ./tmp\")", "(file-exists? \"./tmp/demo.txt\")", "(file-exists? \"./tmp/nichtda.txt\")"]),
    dict(cat="Datei-I/O", name="file-delete", syntax="(file-delete \"pfad\")", desc="Löscht eine Datei. Gibt t zurück.",
         examples=["(system \"mkdir -p ./tmp\")", "(file-write \"./tmp/demo.txt\" \"x\")", "(file-delete \"./tmp/demo.txt\")"]),

    # ---- Nebenläufigkeit ----
    dict(cat="Nebenläufigkeit", name="chan-make", syntax="(chan-make)  bzw.  (chan-make n)",
         desc="Erzeugt einen Channel (optional mit Puffergröße n).",
         examples=["(define ch (chan-make))", "(define ch2 (chan-make 10))"]),
    dict(cat="Nebenläufigkeit", name="chan-send", syntax="(chan-send ch wert)", desc="Sendet einen Wert in einen Channel.",
         examples=["(chan-send ch 42)"]),
    dict(cat="Nebenläufigkeit", name="chan-recv", syntax="(chan-recv ch)", desc="Empfängt einen Wert aus einem Channel (blockierend, wenn leer).",
         examples=["(chan-recv ch)"]),
    dict(cat="Nebenläufigkeit", name="lock-make", syntax="(lock-make)", desc="Erzeugt einen Mutex für lock.",
         examples=["(define mu (lock-make))"]),

    # ---- KI ----
    dict(cat="KI", name="sigo", syntax="(sigo prompt [modell] [session-id] [host])",
         desc="Sendet einen Prompt an sigoREST und gibt die Antwort als String zurück. Default-Modell und Host können via Env-Variablen gesetzt werden.",
         examples=["(sigo \"Erkläre TCO\")", "(sigo \"Hallo\" \"cl46-s\")"]),
    dict(cat="KI", name="sigo-models", syntax="(sigo-models)", desc="Liefert eine Liste der verfügbaren sigoREST-Modelle.",
         examples=["(sigo-models)"]),
    dict(cat="KI", name="sigo-host", syntax="(sigo-host \"http://...\")", desc="Setzt oder liest den sigoREST-Host.",
         examples=["(sigo-host \"http://mammouth:9080\")"]),

    # ---- Zeit ----
    dict(cat="Zeit", name="sleep", syntax="(sleep ms)", desc="Pausiert für die angegebene Anzahl Millisekunden.",
         examples=["(sleep 100)", "(sleep 2000)"]),

    # ---- Memory ----
    dict(cat="Memory", name="memstats", syntax="(memstats)", desc="Liefert Go-Runtime-Memory-Statistiken als Assoziationsliste.",
         examples=["(memstats)", "(assoc 'heapalloc (memstats))"]),

    # ---- Shell & System ----
    dict(cat="Shell & System", name="system", syntax="(system \"shell-kommando\")",
         desc="Führt ein Shell-Kommando aus und gibt den Exit-Code zurück (0 = OK).",
         examples=["(system \"echo hallo\")", "(system \"test -f ./tmp/demo.txt\")"]),
    dict(cat="Shell & System", name="file-stat", syntax="(file-stat \"pfad\")",
         desc="Liefert eine Assoziationsliste mit size und mtime oder nil, wenn die Datei nicht existiert.",
         examples=["(system \"mkdir -p ./tmp\")", "(file-write \"./tmp/demo.txt\" \"Hallo\")", "(file-stat \"./tmp/demo.txt\")", "(assoc 'size (file-stat \"./tmp/demo.txt\"))"]),
    dict(cat="Shell & System", name="assoc", syntax="(assoc key alist)",
         desc="Sucht das erste Paar (key . val) in einer Assoziationsliste mittels equal?.",
         examples=["(assoc 'b '((a . 1) (b . 2) (c . 3)))", "(assoc 'x '((a . 1)))"]),
    dict(cat="Shell & System", name="symbol->string", syntax="(symbol->string 'symbol)",
         desc="Wandelt ein Symbol in seinen String-Namen um.",
         examples=["(symbol->string 'foo)", "(symbol->string 'my-var)"]),

    # ---- PostgreSQL ----
    dict(cat="PostgreSQL", name="pg-connect", syntax="(pg-connect \"connection-string\")",
         desc="Öffnet eine PostgreSQL-Verbindung. Connection-String z.B. host=... port=... user=... password=... dbname=...",
         examples=["(define conn (pg-connect \"host=localhost user=golisp dbname=test sslmode=disable\"))"]),
    dict(cat="PostgreSQL", name="pg-query", syntax="(pg-query conn \"SELECT ...\" param ...)",
         desc="Führt eine SELECT-Abfrage aus und gibt eine Liste von Zeilen (Assoziationslisten) zurück.",
         examples=["(pg-query conn \"SELECT * FROM users WHERE id = $1\" 42)"]),
    dict(cat="PostgreSQL", name="pg-exec", syntax="(pg-exec conn \"INSERT/UPDATE ...\" param ...)",
         desc="Führt eine schreibende Abfrage aus und gibt die Anzahl betroffener Zeilen zurück.",
         examples=["(pg-exec conn \"INSERT INTO users (name) VALUES ($1)\" \"Alice\")"]),
    dict(cat="PostgreSQL", name="pg-close", syntax="(pg-close conn)", desc="Schließt eine PostgreSQL-Verbindung.",
         examples=["(pg-close conn)"]),

    # ---- Standardbibliothek (lib/stdlib.lisp) ----
    dict(cat="Standardbibliothek", name="cadr", syntax="(cadr liste)", desc="Kurzform für (car (cdr liste)).",
         examples=["(cadr '(1 2 3))", "(cadr '(a b c))"]),
    dict(cat="Standardbibliothek", name="caddr", syntax="(caddr liste)", desc="Kurzform für (car (cdr (cdr liste))).",
         examples=["(caddr '(1 2 3))", "(caddr '(a b c d))"]),
    dict(cat="Standardbibliothek", name="cadddr", syntax="(cadddr liste)", desc="Kurzform für (car (cdr (cdr (cdr liste)))).",
         examples=["(cadddr '(1 2 3 4))"]),
    dict(cat="Standardbibliothek", name="cddr", syntax="(cddr liste)", desc="Kurzform für (cdr (cdr liste)).",
         examples=["(cddr '(1 2 3))", "(cddr '(a b c d))"]),
    dict(cat="Standardbibliothek", name="cdar", syntax="(cdar liste)", desc="Kurzform für (cdr (car liste)).",
         examples=["(cdar '((a b c)))"]),
    dict(cat="Standardbibliothek", name="caar", syntax="(caar liste)", desc="Kurzform für (car (car liste)).",
         examples=["(caar '((a b)))"]),
    dict(cat="Standardbibliothek", name="first", syntax="(first liste)", desc="Alias für car.",
         examples=["(first '(a b c))"]),
    dict(cat="Standardbibliothek", name="second", syntax="(second liste)", desc="Alias für cadr.",
         examples=["(second '(a b c))"]),
    dict(cat="Standardbibliothek", name="third", syntax="(third liste)", desc="Alias für caddr.",
         examples=["(third '(a b c))"]),
    dict(cat="Standardbibliothek", name="fourth", syntax="(fourth liste)", desc="Alias für cadddr.",
         examples=["(fourth '(a b c d))"]),
    dict(cat="Standardbibliothek", name="rest", syntax="(rest liste)", desc="Alias für cdr.",
         examples=["(rest '(a b c))"]),
    dict(cat="Standardbibliothek", name="zero?", syntax="(zero? n)", desc="Gibt t zurück, wenn n gleich 0 ist.",
         examples=["(zero? 0)", "(zero? 5)"]),
    dict(cat="Standardbibliothek", name="positive?", syntax="(positive? n)", desc="Gibt t zurück, wenn n größer als 0 ist.",
         examples=["(positive? 5)", "(positive? -1)"]),
    dict(cat="Standardbibliothek", name="negative?", syntax="(negative? n)", desc="Gibt t zurück, wenn n kleiner als 0 ist.",
         examples=["(negative? -3)", "(negative? 1)"]),
    dict(cat="Standardbibliothek", name="pair?", syntax="(pair? x)", desc="Gibt t zurück, wenn x ein Cons / keine Atom ist.",
         examples=["(pair? '(1 2))", "(pair? 5)"]),
    dict(cat="Standardbibliothek", name="when", syntax="(when test body ...)", desc="Makro: wertet body nur aus, wenn test wahr ist.",
         examples=["(when t 'ja)", "(when nil 'nein)"]),
    dict(cat="Standardbibliothek", name="unless", syntax="(unless test body ...)", desc="Makro: wertet body nur aus, wenn test falsch ist.",
         examples=["(unless nil 'ja)", "(unless t 'nein)"]),
    dict(cat="Standardbibliothek", name="append", syntax="(append lst1 lst2)", desc="Hängt zwei Listen aneinander.",
         examples=["(append '(1 2) '(3 4))", "(append '(a) '(b c d))"]),
    dict(cat="Standardbibliothek", name="reverse", syntax="(reverse liste)", desc="Dreht eine Liste um.",
         examples=["(reverse '(1 2 3))", "(reverse '(a b c d))"]),
    dict(cat="Standardbibliothek", name="length", syntax="(length liste)", desc="Liefert die Anzahl der Elemente einer Liste.",
         examples=["(length '(1 2 3))", "(length '())"]),
    dict(cat="Standardbibliothek", name="nth", syntax="(nth n liste)", desc="Liefert das n-te Element einer Liste (0-basiert).",
         examples=["(nth 0 '(a b c))", "(nth 2 '(a b c))"]),
    dict(cat="Standardbibliothek", name="last", syntax="(last liste)", desc="Liefert das letzte Element einer Liste.",
         examples=["(last '(1 2 3))", "(last '(a b))"]),
    dict(cat="Standardbibliothek", name="member", syntax="(member x liste)", desc="Sucht x in einer Liste und gibt die Restliste ab dem Treffer zurück.",
         examples=["(member 'b '(a b c))", "(member 'x '(a b c))"]),
    dict(cat="Standardbibliothek", name="assoc", syntax="(assoc key liste)", desc="Sucht key in einer Assoziationsliste und gibt das erste passende (key val)-Paar zurück.",
         examples=["(assoc 'b '((a 1) (b 2) (c 3)))", "(assoc 'x '((a 1)))"]),
    dict(cat="Standardbibliothek", name="filter", syntax="(filter pred liste)", desc="Liefert alle Elemente, für die die Prädikatfunktion wahr ist.",
         examples=["(filter (lambda (x) (> x 2)) '(1 2 3 4))", "(filter atom? '((1 2) a (3 4) b))"]),
    dict(cat="Standardbibliothek", name="reduce", syntax="(reduce f init liste)", desc="Faltet eine Liste mit einer Funktion und einem Startwert zusammen.",
         examples=["(reduce + 0 '(1 2 3 4))", "(reduce * 1 '(1 2 3 4))"]),
    dict(cat="Standardbibliothek", name="for-each", syntax="(for-each f liste)", desc="Wendet f auf jedes Element an, gibt nil zurück.",
         examples=["(for-each println '(1 2 3))", "(for-each (lambda (x) (print (* x x))) '(2 3))"]),
    dict(cat="Standardbibliothek", name="any", syntax="(any pred liste)", desc="Gibt t zurück, wenn mindestens ein Element die Prädikatfunktion erfüllt.",
         examples=["(any (lambda (x) (> x 5)) '(1 2 6))", "(any (lambda (x) (> x 5)) '(1 2 3))"]),
    dict(cat="Standardbibliothek", name="every", syntax="(every pred liste)", desc="Gibt t zurück, wenn alle Elemente die Prädikatfunktion erfüllen.",
         examples=["(every number? '(1 2 3))", "(every number? '(1 a 3))"]),
    dict(cat="Standardbibliothek", name="flatten", syntax="(flatten liste)", desc="Entfernt eine Ebene von Verschachtelungen; rekursiv flach.",
         examples=["(flatten '((1 2) (3 (4))))", "(flatten '(a (b c) d))"]),
    dict(cat="Standardbibliothek", name="zip", syntax="(zip lst1 lst2)", desc="Verbindet zwei Listen elementweise zu Paaren.",
         examples=["(zip '(1 2) '(a b))", "(zip '(1 2 3) '(a b))"]),
    dict(cat="Standardbibliothek", name="list-tail", syntax="(list-tail liste n)", desc="Liefert den n-ten Rest der Liste.",
         examples=["(list-tail '(1 2 3) 0)", "(list-tail '(1 2 3) 2)"]),
    dict(cat="Standardbibliothek", name="iota", syntax="(iota n)", desc="Erzeugt die Liste (0 1 ... n-1).",
         examples=["(iota 5)", "(iota 0)"]),
    dict(cat="Standardbibliothek", name="square", syntax="(square x)", desc="Quadriert x.",
         examples=["(square 5)", "(square 3)"]),
    dict(cat="Standardbibliothek", name="expt", syntax="(expt base exp)", desc="Berechnet base hoch exp (exp ganze Zahl, rekursiv).",
         examples=["(expt 2 10)", "(expt 3 3)"]),
    dict(cat="Standardbibliothek", name="gcd", syntax="(gcd a b)", desc="Berechnet den größten gemeinsamen Teiler.",
         examples=["(gcd 48 18)", "(gcd 100 35)"]),
    dict(cat="Standardbibliothek", name="dotimes", syntax="(dotimes (var n) body ...)", desc="Makro: wiederholt body für var von 0 bis n-1.",
         examples=["(dotimes (i 3) (print i))", "(dotimes (i 3) (println (* i i)))"]),
    dict(cat="Standardbibliothek", name="dolist", syntax="(dolist (var liste) body ...)", desc="Makro: iteriert über eine Liste.",
         examples=["(dolist (x '(1 2 3)) (print x))", "(dolist (c '(\"a\" \"b\")) (println c))"]),
    dict(cat="Standardbibliothek", name="push", syntax="(push wert var)", desc="Makro: fügt wert am Anfang der Liste in var ein.",
         examples=["(define s '())", "(push 1 s)", "(push 2 s)", "s"]),
    dict(cat="Standardbibliothek", name="pop", syntax="(pop var)", desc="Makro: entfernt und liefert das erste Element der Liste in var.",
         examples=["(define s '(1 2 3))", "(pop s)", "s"]),
    dict(cat="Standardbibliothek", name="alist-set", syntax="(alist-set key val liste)", desc="Setzt oder ersetzt einen Eintrag in einer Assoziationsliste.",
         examples=["(alist-set 'b 99 '((a 1) (b 2)))", "(alist-set 'd 4 '((a 1)))"]),
    dict(cat="Standardbibliothek", name="alist-get", syntax="(alist-get key liste)", desc="Liefert den Wert zu key aus einer Assoziationsliste oder nil.",
         examples=["(alist-get 'b '((a 1) (b 2)))", "(alist-get 'x '((a 1)))"]),
    dict(cat="Standardbibliothek", name="identity", syntax="(identity x)", desc="Gibt x unverändert zurück.",
         examples=["(identity 42)", "(identity '(1 2 3))"]),
    dict(cat="Standardbibliothek", name="constantly", syntax="(constantly x)", desc="Liefert eine Funktion, die bei jedem Aufruf x zurückgibt.",
         examples=["((constantly 5) 'a 'b)", "((constantly 'ok) 1 2 3)"]),
    dict(cat="Standardbibliothek", name="complement", syntax="(complement f)", desc="Liefert das logische Komplement einer Funktion.",
         examples=["((complement null?) '(1 2))", "((complement zero?) 5)"]),
    dict(cat="Standardbibliothek", name="compose", syntax="(compose f g)", desc="Liefert eine Funktion, die f(g(x)) auf ein Argument anwendet.",
         examples=["((compose number->string (lambda (x) (* x 2))) 5)", "((compose string-upcase symbol->string) 'foo)"]),
]
